<?php

$poems = array();

// ------------------------- Emerald Raptor -----------------------------
$poems[] = array("title" => "Loppa", "author" => "Emerald Raptor", "text"=> 
"Det var en gang
ei loppe
som var så flink
'tå hoppe
til slutt så
måtte'n stoppe
for lokke' vakke'
oppe");

$poems[] = array("title" => "Dragemagen", "author" => "Emerald Raptor", "text"=> "Har du hørt om dragen
som satt og gråt i hagen
Den hadde spist en hamburger
og fått så vondt i magen

Lille, søte drage gul
sa en liten sommerfugl
Nå er det ikke lengre jul
og magen din har fått en kul!

Jeg synes du er kjempesær
som ikke spiser bringebær
da får du på deg dine klær
og det er fullt i hagen her!

Dragen sa: Hipp hurra
Nå skal magen min bli bra
Jeg spiser bær, takk skal du ha,
Lykkelig og kjempegla'!");


// ------------------------- Gunnar R Tjomlid -----------------------------

$poems[] = array("title" => "Tåren", "author" => "Gunnar R Tjomlid", "text"=>  
"Tørk bort mine tårer
men la en få renne fritt.
La den seile uten årer
ned langs hele kinnet mitt.

Se, min tåre er det savnet
som jeg aldri helt forlot;
hver en gang jeg hørte navnet,
slo det atter en gang rot.

Nå kan tåren min få tørke,
la den dampe sakte vekk,
og med den forsvinner mørket;
det som engang var en bekk.

Nå skal kjærligheten strømme
og ta tårens tomme sted;
for så lenge jeg kan drømme,
kan tåren min få fred.");

$poems[] = array("title" => "Viske, viske, viske", "author" => "Gunnar R Tjomlid", "text"=>  
"Viske, viske, viske 
meg bort 
du 
ditt dumme viskelær 
uten nagler eller 
ring i nesen 
eller noe annet som 
kan skremme 
en stakkars 
selvdestruktiv blyantstrek.");

$poems[] = array("title" => "Verden i vinduet", "author" => "Gunnar R Tjomlid", "text"=>  
"Jeg ser ut av vinduet, 
ser en enkel verden. 
Verden slik mange ønsker den. 
Ukomplisert. Straight. 
Og jeg ønsker meg en karm i 
livet mitt, slik 
at hverdagen min 
blir som verden 
i vinduet.");

$poems[] = array("title" => "Til...", "author" => "Gunnar R Tjomlid", "text"=>  
"Igjen. 
Og uten et ord. 
Hva kan vel jeg si av betydning 
når jeg er i nærvær av 
dette mennesket? 
Hva kan vel jeg si av betydning 
som kan måles mot den 
sprudlende latter og snøskred 
av en monolog som får meg til å 
atter nyte livet. 
Så jeg bruker heller tiden 
til å betrakte. 
Kan ingenting annet enn å se 
på henne. 
På deg. 
Igjen.");

$poems[] = array("title" => "Se det!", "author" => "Gunnar R Tjomlid", "text"=>  
"Se det! Nå står vi her, 
alene, du og jeg. 
Se det! Du tygger Hubba 
Bubba eller Toy? 
Se det! Du blåser bobler, 
så store de kan bli! 
Se det! Nå har vi stått her 
i nesten ti minutt. 
Se det! Du snur meg ryggen 
og løper sakte bort. 
Se det! Jeg har gjort tabben, 
jeg dreit meg ut igjen. 
Se det! Se det!");

$poems[] = array("title" => "Savn", "author" => "Gunnar R Tjomlid", "text"=>  
"Så er det natt igjen. Rommet 
tar imot stillheten med åpne armer, 
uten å tenke på meg. 
Jeg må la meg bli knust 
under alle tankene som igjen 
får rom inni hodet mitt. Tankene om 
deg. 
Stillheten omkring meg gir ingen 
plass til lengselen min, så jeg blir sittende 
igjen med den. 
Og den sprenger meg innenfra. 
Lengselen som jeg må takle 
alene, 
selv om det kun er oss sammen 
som kan fjerne den.");

$poems[] = array("title" => "Når", "author" => "Gunnar R Tjomlid", "text"=>  
"Kan det komme 
en tid, 
når ingen lenger 
venter på at 
det skal komme 
en tid?");

$poems[] = array("title" => "Naturmennesket", "author" => "Gunnar R Tjomlid", "text"=>  
"Jeg ser på trærne. De ser 
så triste ut der de står i 
pøsregnet. Grenene henger ned 
som visne armer. Ensomme, selv 
om de står midt i skogen. 
Rastløse, selv om de står på 
samme sted som i fjor. Venter 
på at noe skal skje, men 
det gjør aldri det. 
Så er vel mennesket som 
trærne, tenker jeg, og 
fyrer på med ved.");

$poems[] = array("title" => "Mennesket og universet", "author" => "Gunnar R Tjomlid", "text"=>  
"Og enda blir alt større, og 
enda mindre. Mens vi 
står her 
på midten og ser alt 
vi engang kunne fange inn 
og begripe 
forsvinne i begge retninger. 
Mens vi står her 
på midten og prøver 
desperat å favne om det hele, 
for så å kunne dra det inn 
og forene begge ytterpunktene 
til en setning. 
Men jo nærmere vi når 
det ene ytterpunktet, jo mer 
fjernes vi fra det andre. Så 
istedenfor forener vi skolissene 
i en knute 
og jogger tre mil.");

$poems[] = array("title" => "Ensomt forelsket", "author" => "Gunnar R Tjomlid", "text"=>  
"Det er litt latterlig
det hele
at det skulle gjøre
mer vondt
å finne kjærligheten
enn å miste den");


// ------------------------- tidslinjer -----------------------------

$poems[] = array("title" => "jeg skal spise min frihet", "author" => "tidslinjer", "text"=>  
"det var da jeg skulle 
knyte vimpelen 
på sannheten

at jeg kom på jeg
hadde glemt saltkorn
så altfor lenge 
fra havet
som bølger i meg

jeg skal 
spise min frihet med 
smak av basilikum
timian og ørlite chili

fra en kyst jeg enda ikke kjenner
og kan kalle mitt hjem");


$poems[] = array("title" => "?", "author" => "tidslinjer", "text"=>  
"...alt er slettet...
radert ut
ingenting igjen
ikke et komma
ikke så mye som en apostrof
eller gåsetegn

bare spørsmålstegnet står der
for egen regning
det skulle vært 
utropstegnet
bak gleden
men kun et krokete 
spørsmålstegn står der
tynget ned av
ti tonn 
- hva nå?

kan jeg 
sette punktum
en gang?

om 100.000 år?
kanskje?");


$poems[] = array("title" => "Gravemaskinenes språk", "author" => "tidslinjer", "text"=>  
"hyles ut av store armer
smal, gul .
med skuffe 
sorte hydraulikkslanger med trykk
og oljeeim i luften
haugene av gråsvartmasse 
på kanten stadig større
graver
seg nedover, nedover 
med gule, sterke, metallarmer 

svinger seg grasiøst (nesten) 
i en dans med moderne korrigrafi
tenner på skuffen spiser seg nedover
i jordkloden, på jakt, 
med formålet klart (jeg er forvirret). 
lys på hjullastere
tunge maskiner som kjører"); 


$poems[] = array("title" => "Forelsket", "author" => "tidslinjer", "text"=>  
"Jeg tørker støv
av sirkelen
der jeg runde 
på runde 
spinner og polerer 
den skinnende glorien.

Ubevisst.
Ufrivillig. 

Med glød.
Varme.

Lenket til den
buede bevegelsen
i min egen tanke.

Jeg kaller meg fri.

Fri; jeg sirkler rundt
og runder sirkelen
gang på gang.
Tanke for tanke
uten tanke 
for annet
enn det lysende varme
i bevegelsens
midtpunkt:

Deg.");

$poems[] = array("title" => "Gal av deg", "author" => "tidslinjer", "text"=>  
"det lille skjelvet
i øyelokket 
før du våkner

gjør at jeg bygger broer
herfra til derfra
og hundre mil unna

like her
jeg er");


$poems[] = array("title" => "Oriontåken M42", "author" => "tidslinjer", "text"=>  
"universet åpner seg 
i meg med undring

når stjernebilder 
følges med en finger

mellom 

lyspunkt uendelig borte
i ditt Orions belte"); 


$poems[] = array("title" => "Utover innenfra", "author" => "tidslinjer", "text"=>  
"Utover i meg selv
innenfra

kommer følelsen av 

vektløshet

bølgene slår 
fører noe bort
alt skylles tilbake

litt om litt

alene");


$poems[] = array("title" => "Smaken av blått", "author" => "tidslinjer", "text"=>  
"Du er så 
blå,
sa jeg. 
Blå?
Spurte du. 
Hvorfor ikke
gul, 
eller sort.
Grønn, kanskje? 

Nei, 
du er blå,
sa jeg. 
Blå for 
blåbær
blå himmel
noe friskt
rent
nytt.

Det er ikke 
blå
sa du.
Det er 
smaken av
galskap"); 


$poems[] = array("title" => "forskjøvet lengsel", "author" => "tidslinjer", "text"=>  
"jeg har glemt 
deg
sier hun stille

rørte du ved
klippene mine
i stormen?

pulsen hans
mot håndflatene 
blir farget lilla

og hun husker");


$poems[] = array("title" => "løsningen", "author" => "tidslinjer", "text"=>  
"hun prøver å gjenkjenne 
en og annen tone
blant menneskene  
som går til og fra
latter og stemmer
smiler jatakk til mer kaffe
ansiktet vendt mot ruten
blikket søkende den veien
det hun vil se
finnes ikke der
tanker om at noe
er med henne
at utgangen
er inngangen
til noe annet
snurrer i tankene
mens hånden hviler på den
slitte bordduken");


// ------------------------- Oddvar Jersin -----------------------------

$poems[] = array("title" => "Knytt ilag", "author" => "Oddvar Jersin", "text"=>  
"Knytt til deg
i varme fargar
vevre minner
endå ikkje
vevd

laga i lag

Skapa von 
von ein...
ein eig

Lik ein blom
ein tykkjer ...");


$poems[] = array("title" => "Blomar i meg", "author" => "Oddvar Jersin", "text"=>  
"For alle kalde
vintrar eg bar
I all frosten
eg sov

Tinte glea i
deg...
meg

Og blomar 
i ord
La du att på puta
mi

Var morgon raud
i meg
Djupare, vakrare,
venare

... enn eg minnes ...

om");


$poems[] = array("title" => "Vær i orda mine", "author" => "Oddvar Jersin", "text"=>  
"Kom
ligg her
hos meg
vær mi ei
lita stund
Kom
vær i orda mine
vær i augene mine
vær i draumane mine
vær alt du er
hjå meg

I kveld");


$poems[] = array("title" => "To raude drops", "author" => "Oddvar Jersin", "text"=>  
"To raude
drops i
lomma
dei svir
og brenner
varmt

Det eine
har eg 
smakt på
det andre
er... 

til deg");


$poems[] = array("title" => "I supermann sovedrakt", "author" => "Oddvar Jersin", "text"=>  
"No ligg du der
å søv
Heile du, er
vetle deg

Gøymd lunt under dyna
svett nakke
ord berre du ser

Ei glea, ein varme
velt imot

Så flyg viare i drøymeverd
du guten min
I supermann sovedrakt");


$poems[] = array("title" => "Vaken draum", "author" => "Oddvar Jersin", "text"=>  
"Med augene att
skin sola i deg

Med augene att
smilar du til meg

Med augene att
bles vinden vår veg

Med augene att
held du kring meg

Med augene åpne
er eg hjå deg...");


$poems[] = array("title" => "Von i regnet", "author" => "Oddvar Jersin", "text"=>  
"Så går eg aleina
i elver av asfalt.
Aleina ilag med alle.
Mørke, våte, sakte skritt.

Natt, igjen...

Låser opp, og tar av meg
hausten,
heng den på knaggen.
Legg frå meg nøklane,
gatene, somrane, minnene...

Kryp inn i svevnen.
Og veit eg har ein
arm å kvila tankane på.");


$poems[] = array("title" => "Skuggelause slag", "author" => "Oddvar Jersin", "text"=>  
"Med sommarfuglevengeslag
i havskodde og røyk.
Kom ord i meg,
og vekte gamal vår.

Vekk var frosen vinterskrud
med frostroser og is.
Eg smilte varmt med heile meg,
mintes det som var.

Så tok eg fyrste skritt på veg,
mot ukjend mark og skog.
Der bekkar klukkar, leikar lett
kring gamle nåletrær.

Men turen vart meir enn lang,
og bratte bakkar mot.
Då segla det ein sommarfugl
med skuggelause slag.

Den kom med last av sommarvind,
og morgonkloke ord.
Eg tok dei med som nistemat,
mot uro djupt i meg.

Så takk min vakre sommarfugl,
for vegen som eg fekk.
Sjølv om du ikkje viste det,
var stien i frå deg.");


$poems[] = array("title" => "Eldfloga", "author" => "Oddvar Jersin", "text"=>  
"I stjernene var eg
ei vinternatt
langt ute i den
kolsvarte øda

Eg sveva ikring
fredlaus og vill
og lysa eg såg
var jorda

Liten og tander
så vever så fin
Eg greip ho med
eine handa

Ho surra litt
eg lot ho gå
for kven vil vel eige
verda");


$poems[] = array("title" => "Glør", "author" => "Oddvar Jersin", "text"=>  
"Stille lagar
du eit
bål av ord

Eit ein kan
varma seg
på

leggja seg
til

Og eg vaknar
til glør
av minner");


// ------------------------- Monica Iselin Evang -----------------------------

$poems[] = array("title" => "Sove", "author" => "Monica Iselin Evang", "text"=>  
"Øyelokkene ramler igjen
Dagen har vært lang
Ute er det mørkt og stille
Sengen lokker

Dagen har vært arbeidsom
Sliten, trøtt og støl
Vil sove i ro
La dag være dag
Og sove");

$poems[] = array("title" => "Kleggen", "author" => "Monica Iselin Evang", "text"=>  
"Der var han
Den lille kleggen
Der stakk han
På jente leggen
Hun hylte og slo ham ned
Du stakk meg! 
Kan tro det sved!

Men kleggeliten
Var ganske sta
Han var litt sliten
Men levde da
Han tok på hatten
Og fløy så opp
Så stakk han katten
Til den sa stopp

Så kattemjauen
Fikk seg et bitt
Og etter ”au”-en
Så sa den ”Skitt!”
Den tok så dyret
Inn i sin munn
Så levde styret
En liten stund");

$poems[] = array("title" => "Hold pusten", "author" => "Monica Iselin Evang", "text"=>  
"Hold pusten akkurat nå
Gjennom hele diktet
Piano
Piano 
Var det non som sa no?
Ikke pust!
Men klø deg litt på nesen
Kjenn hvordan lungene er fulle på spreng");

$poems[] = array("title" => "Det dundrer i bakken", "author" => "Monica Iselin Evang", "text"=>  
"Det dundrer i bakken
Av harde hestehover
Jeg kjenner vibrasjonene
Jeg vet at et enormt tungt vesen 
Er på vei mot meg 
I en ufattelig fart

Hvis jeg ikke flytter meg
Blir jeg trampet i hjel
Den kommer nærmere
Jeg hører høvene gnistre mot steiner i bakken
Jeg ser de villsprengte øynene

Jeg spenner meg
Trekker pusten
Klar til et enormt hopp
Men ombestemmer meg
Lar hesten komme
Mot meg
Hiver meg etter den lange manen
Armene mine blir med ett revet framover i en vill fart
Jeg må skynde meg
Hopper til 
Lar meg dra med
I et vilt sug
Og får beinet over hesteryggen
Før den har løpt fra meg
Klatrer opp
På ryggen til det bevegende dyret
Kjenner rytmen og takten
Dunder i bakken

Jeg lever");


$poems[] = array("title" => "En naken rygg", "author" => "Monica Iselin Evang", "text"=>  
"En naken rygg
Til en jeg kjenner
Nå ser jeg midjen din
Snart er du her
I sengen hos meg");


$poems[] = array("title" => "Blå is", "author" => "Monica Iselin Evang", "text"=>  
"Blå is
Vinden blåser
Kald bris
Over åser

Varmt kull
Ilden brenner
Mørkt gull
Som vi tenner");


$poems[] = array("title" => "Varm gutt", "author" => "Monica Iselin Evang", "text"=>  
"Varm gutt
Gir jente frysninger");


$poems[] = array("title" => "Vann", "author" => "Monica Iselin Evang", "text"=>  
"Vann
Renner
Sildrer
Leker
Snirkler
Bruser
Sprudler og
spruter");

$poems[] = array("title" => "Trollet i skatollet", "author" => "Monica Iselin Evang", "text"=>  
"Trollet i skatollet
Det magiske skatollet
Skatollet med trollet

Det er et troll i mitt skatoll
et magisk troll som synger i moll
rock'n roll
tar en stroll");


// ------------------------- M.E. -----------------------------

$poems[] = array("title" => "Bug", "author" => "M.E.", "text"=>  
"Se paa maanen! 
Der den triller nedover gata 
Oppi en hestemoekk 
og ned i et hull
 
Faelt saa moerkt det ble... 
Kan du se noe? 
Ogsaa midt paa natta da! 
Bare sola ikke har faatt samme skjebne...
 
Der kommer det noen 
De fisker opp maanen fra hullet 
Men uff saa moekkete den er 
Og den stinker!
 
De henger den paa plass 
Men verden er liksom ikke den samme lenger...");


$poems[] = array("title" => "HEI DU DUMME GAMLE MANN DER BORTE", "author" => "M.E.", "text"=>  
"Hei du dumme gamle mann der borte. 
Kom hit og hjelp meg! 
Jeg trenger din hjelp saa saart, 
vaer saa snill!
 
Hei du dumme gamle mann der borte, 
ikke bare staa der og glo! 
Kom og hjelp meg da vel! 
Jeg klarer ikke dette alene.
 
Hei du dumme gamle mann der borte, 
ser du ikke at jeg trenger hjelp? 
Kom naa. 
Og sett deg paa den andre enden 
av dumphuska.");  


$poems[] = array("title" => "Edderkoppen", "author" => "M.E.", "text"=>  
"Bortover bakken med alle barna på ryggen 
Skal hente gubben som spiller kort
 
Plutselig - en skygge så mørk, rett over 
Og så er edderkoppen bare gørr...");


$poems[] = array("title" => "TRE SNILER", "author" => "M.E.", "text"=>  
"Flipp-flopp, 
en sild, en stopp 
For mange andre biler
 
Kaputt-kaplonk 
en diger jånk 
Det kryper det tre sniler"); 


$poems[] = array("title" => "Vampyrens Livrett", "author" => "M.E.", "text"=>  
"Museblod er rødt 
Kongeblod er blått
 
Men begge deler smaker like godt"); 


$poems[] = array("title" => "Å grave seg ned", "author" => "M.E.", "text"=>  
"Jeg vil grave meg ned! 
Grave et stort, dypt hull i bakken. 
I jorda. 
Langt ned.
 
Så kan de andre bare sitte der på overflata 
med skjegget i postkassa. 
Mens jeg sitter nedi hullet mitt 
og har det fint.
 
Jeg vil ned til markene og 
billene. Til muldvarpene som ikke ser. 
Til jordrotter og tusenbein, 
maur og andre dyr.
 
For de er ikke slemme! 
De lar meg være i fred hvis 
jeg lar dem være i fred. 
Der finnes ingen politikk, eller debatter og diskusjoner.
 
Der vil jeg bade i underjordiske 
sjøer og bekker. 
Og jeg vil klappe muldvarpen og 
hjelpe den å grave flere ganger.
 
Der vil jeg bli til jeg en dag blir lei. 
Da krabber jeg opp igjen 
til de andre 
og finner ut at de ikke har savnet meg.");


$poems[] = array("title" => "HIMMELENS HEMMELIGHET", "author" => "M.E.", "text"=>  
"I en liten skydott 
der snoekrystaller bor 
vil solens myke straaler 
bli hvite boelgespor
 
Naar vinden dotten skyver 
ni meter per sekund 
vil dottens snoekrystaller 
faa forme dotten rund
 
Nedenfor meg ser jeg 
at denne hvite prikk 
blir stoerre foer det kiler 
av snoekrystallers stikk");


$poems[] = array("title" => "Høst", "author" => "M.E.", "text"=>  
"Nå kommer snart høsten. 
Nå er snart bladene gule, 
hvertfall litt. 
Nå regner det oftere og oftere, 
og fuglene flyr hjem.
 
Det blir kaldt å gå fra toget 
om morgenen. 
Det digitale termometeret 
er snart ett-sifret. 
Jeg venter på at dagene skal 
bli enda kortere.
 
Da kan vi endelig prøve den nye baklykta 
til sykkelen!");


$poems[] = array("title" => "En marketur", "author" => "M.E.", "text"=>  
"Lille marken sitter på kvisten,
ytterst på kvisten
 
Åler seg framover 
milimeter for milimeter 
på den tynne tynne kvisten
 
Matte lysegrønne kuler 
på rekke og rad 
i solstrålene
 
Uten øyne, 
uten å vite hvor langt 
det er ned
 
Endelig når den 
bjørkebladet, 
reisens mål
 
Jafser i seg 
store flak 
Blir enda rundere
 
Tygger og tygger, 
til baldet er helt 
borte
 
Da snur den seg 
og krabber videre 
til et nytt blad");


$poems[] = array("title" => "Musa", "author" => "M.E.", "text"=>  
"En mus kryper sakte av gårde. 
Den kan ikke riktig stå stille! 
Litt opp, litt ned. 
Og så til siden.
 
Plutselig farer den opp, 
som om det er noe den 
plutselig kommer på. 
Like plutselig stopper den 
og legger seg ned igjen.
 
Så bli klokken fire, og 
endelig kan den få sove 
i fred. 
Den kryper sammen 
i det ene hjørnet av 
musematta.");


$poems[] = array("title" => "Punsjknapper", "author" => "M.E.", "text"=>  
"Er deilige 
De har saanne gode hvite frø utenpå 
som man kan tygge så det knaser 
Man kan tygge lenge paa dem 
for det er saa mange av dem 

Punsjknapper er saa gode inni! 
Den gode karamellsmaken blir jeg aldri lei 
Den smelter paa tunga 
Er søt og god 
nam nam nam
 
Og sjokoladetrekket mellom karamellen og frøene 
er det beste av alt! 
For den er det minst av."); 


// ------------------------- Futurid -----------------------------


$poems[] = array("title" => "Ta et stykke tid", "author" => "Futurid", "text"=>  
"Ta et stykke tid...
og se på det....

er det noe på stykket ditt
' er det fylt av sand, eller grus, eller stein
eller kanskje vakre smykker

er stykket ditt fylt til randen
med flere lag av alt mulig
så det ikke er noe plass igjen
eller kanskje det bare er en skinnende juvel der

er stykket ditt tomt, kanskje
og står der som et gapende hull
som lengter etter å bli fyllt?

Ta et stykke tid...
tøm det for trivielt innhold
og fyll det med det du ønsker aller mest."); 


$poems[] = array("title" => "Vakker er sannheten", "author" => "Futurid", "text"=>  
"Vakker er sannheten
når den er skjult
som en idyllisk vinter
hvor virkeligheten er
dekket av et hvitt teppe

men vinteren varer ikke evig
det hvite teppet smuldrer opp
og renner alltid bort
fram kommer den brune jord
den nake sannhet
mørk og stygg
blottlagt

men den brune jord
har i seg
spirer til liv

og vakrest er sannheten
når den har vokst til
en grønn og frodig midtsommer
med røtter i
ekte jordbunn."); 


$poems[] = array("title" => "Lille blomst", "author" => "Futurid", "text"=>  
"Lille blomst
du er også et liv
men kan du føle lykke
kan du føle smerte
kan du tenke
kan du snakke -
med andre små blomster
snakker du samme språk -
som den store furua
blir du lei deg
hvis jeg plukker deg"); 


$poems[] = array("title" => "Vintervei", "author" => "Futurid", "text"=>  
"rusler bortover vintervei
skinnende hvit snø
knirker under sko
månen speiler seg
i sillioner små snøkrystaller
granene bukker for meg
og buskaset vinker med nakne hender
og det lukter vinter

etter hvert som jeg går
herlig fred
senker seg
over mitt oprrørte sinn
det var godt å gå en tur
isteden for å sove i kveld");


$poems[] = array("title" => "Male", "author" => "Futurid", "text"=>  
"jeg vil male med farger
smøre dem utover lerettet
sette dem sammen
slik at bildet vibrerer av lys

jeg vil male med ord
spre dem utover arket
slik at spørsmål blir svar
og svar blir spørsmål

jeg vil male med toner
sende dem ut i salen
en og en - flere sammen
slik at lufta bever av intensitet

jeg vil male med bevegelser
danse dem fram
mykt og heftig
slik at huldra svever

jeg vil male på alle måter
samtidig
male med farger på scenen
med musikk og sang og dans
og bildet skal endre seg stadig
og vare circa en og en halv time
hver gang");  


$poems[] = array("title" => "Ensomhet", "author" => "Futurid", "text"=>  
"Ensomhet er
å sitte der
alene for deg selv
med fine klær
og bare knær
når festen er på hell
å ta om glasset som er fylt
med vin av ukjent type
å se din kjære danse vilt
med nok ei sexy rype"); 


$poems[] = array("title" => "Den første fløyelseblomst", "author" => "Futurid", "text"=>  
"Vårens første blå fløyelseblomst
har spurnget ut
vårens andre og tredje blå fløyelsblomst
skal snart springe ut
de følger hakk i hel
og myser beundrende mot den første
deretter skal den fjerde, femte og sjette
springe ut
og alle de andre
til et blått teppe
og den første blå fløyelsblomst
skal visne først
men det er den som vil bli husket"); 

$poems[] = array("title" => "Verden er min", "author" => "Futurid", "text"=>  
"Midt i min verden
er bare jeg
litt bortenfor meg
kan jeg skimte deg
men jeg kan ikke se
noe bortenfor der
er det fordi
der ingenting er?");


$poems[] = array("title" => "Går tiden rundt", "author" => "Futurid", "text"=>  
"Går tiden rundt?
kanskje den har så stor diameter
at vi ikke merker det
og tror at tiden er lineær?

men kanskje vi skulle tro på
at tiden går rundt
slik at vi kunne
gjøre alt på nytt
hver gang nullpunktet går forbi
og gjøre alt
litt bedre
enn forrie gang"); 


$poems[] = array("title" => "Se på himmelen", "author" => "Futurid", "text"=>  
"Se på himmelen lille pike
se på fargene
Silliarder av forskjellige blå farger
noen nyanser hvitt og grått
Bobler fram og lager eventyr

Se på himmelen lille pike
herlig hveld
varmt og behagelig
et glass med noe kaldt i hagegyngen
rammen om kjærlighet

Se på himmelen lille pike
se på månen mellom bjørkene
se på skogene og markene
se på freden
la freden se på oss

Se på himmelen lille pike
når jeg ikke lenger er hos deg
og du velger dine veier selv

Se på himmelen min lille pike
om du skulle lengte
tilbake til denne kveld");  


// ------------------------- En hvit hest -----------------------------

$poems[] = array("title" => "Ettertanke", "author" => "En hvit hest", "text"=>  
"Over alt hvor vi går, setter vi spor
Jeg oppsøker dine

Kjenner varmen du etterlot
på en gjenstand du holdt
spiller låta du
dansa til i går");

$poems[] = array("title" => "", "author" => "En hvit hest", "text"=>  
"når du ler
ser hun skyggene
tydeligere
lyset i latteren gjør kontrastene klarer
skyggene mørkere

i din latter
ser hun håpet, men
i din latter
ser hun håpløsheten enda
klarere

drømmen om deg er
drømmen om alt som
aldri kunne bli
drømmen om alt hun
avviste drømmen
om alt hun
ikke drømmer om");


// ------------------------- Heidi Srand Harboe -----------------------------

$poems[] = array("title" => "Kvinnene strikkar på toget", "author" => "Heidi Srand Harboe", "text"=>  
"Dei strikkar på toget
kvinnene
Strikkar sjølve livet
fast
i gult og lilla ullgarn
Forbi dei nakne trea
dei kalde vatna
den syngande hausten
Smilande, tause
sfinxar
Strikkar seg over fjella.");


$poems[] = array("title" => "Leit etter meg", "author" => "Heidi Srand Harboe", "text"=>  
"Leit etter meg
i gatene
Rop på meg
frå høge hustak
Fortel meg
at her
høyrer eg heime.");

$poems[] = array("title" => "Tornerose", "author" => "Heidi Srand Harboe", "text"=>  
"Bak svevnen
sin sjuande port
kjem du til meg
med orda eg hadde gløymt
for første gong
på hundre år
ser eg blikket ditt
og kjenner deg att.
Oftare
skulle me møtast. ");


$poems[] = array("title" => "Vinternatt", "author" => "Heidi Srand Harboe", "text"=>  
"Siste vinteren
i hus med Astrid
med te og grøne eple
midt på natta
og fingertuppane
litt engstelege mot bordplata
snart skulle alt
bli så annleis.

Du er vakker
seier eg
vakker og sterk
og me ler
for slikt seier ein ikkje.

Sjå ut mot framtida Astrid
og fly
når det blir varmt nok.");



$poems[] = array("title" => "", "author" => "Heidi Srand Harboe", "text"=>  
"Sjå i nåde til oss

Me sit her
på kvar våre tuer

sorterer glas
metall, papir
og plast

strever
med draumen
om finare bil
nyare stove
høgare sko

byggjer oss
kapell
av draumar
lotusblomar
og brennande
lys

går turar
i kjøpesenter
fulle av perler
og krav
fulle av lange korridorar

sjå i nåde til oss
me famnar livet
etter beste evne

og det er då
noko rørande
ved oss.");


$poems[] = array("title" => "Me skulle heller klappa katten", "author" => "Heidi Srand Harboe", "text"=>  
"Ein malande katt
dovent på tastaturet
der du har tenkt å forma ord

kjærteiknar handa di
med ein pote utan klør.

Me skulle vera stille
av og til
stille som soloppgangar
tause som dogg i graset.

Me skulle ta pause
frå radioen
som snakkar og snakkar
frå alle tankane
som spring i frå oss.

Me skulle heller
klappa katten
av og til
og la det andre venta.");


$poems[] = array("title" => "To sovande barn", "author" => "Heidi Srand Harboe", "text"=>  
"To sovande barn
mellom kjærasten min og meg
Prustande snøftande
med bamsar på brystet
Me legg oss i utenkjelege vinklar
for å få plass
veit dei burde berast ut
men sparkande varme
held dei oss vakne
i gyngande halvørske
let me tankane berast
av trygg tung barnepust
til me sovnar lukkelege
ein gong utpå morgonkvisten.");


$poems[] = array("title" => "Noko hemmeleg", "author" => "Heidi Srand Harboe", "text"=>  
"Den vesle jenta
i den store senga
veit noko hemmeleg
Dei tynne armane
er hennar
men ikkje
den krøkte ryggen
dei tome brysta
det lause skinnet på magen
Slikt høyrer ikkje småjenter til
Med eit undrande
blått blikk
Meir uendeleg
enn sjølve tida
Ser ho
det hemmelege rakt i augene.");


$poems[] = array("title" => "Dei farlege orda", "author" => "Heidi Srand Harboe", "text"=>  
"Dei farlege orda
åt seg gjennom tankane
og strødde sengeteppet
med små kantete bitar
av knekkebrød
Om kveldane
stengde eg bråket ute
La meg flat på senga
og leita etter tonane.");


$poems[] = array("title" => "Ut i lyset", "author" => "Heidi Srand Harboe", "text"=>  
"Men så kom sola
gjennom dei skitne vindua mine
Eg stengde døra
til den fulle vaskekjellaren.
og kyste barnet
hardt på truten.
Me snubla oss over støvsugaren
ut i lyset.
Gøymde alle husnøklar
og plukka kvite blomar.");

// -------------------------  -----------------------------

/*
$poems[] = array("title" => "", "author" => "", "text"=>  
"");

Tusen takk til forfatterne som var villige til å dele sine dikt med verden:

tidslinjer
Gunnar R Tjomlid
Oddvar Jersin
Monica Iselin Evang
Futurid
M.E.
Emerald Raptor
En hvit hest
*/


?>
